/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as WorkshopsCodeParticipantsRouteImport } from "./routes/workshops.$code.participants"
import { Route as WorkshopsCodeParticipantsTeamIdRouteImport } from "./routes/workshops.$code.participants_.$teamId"
import { Route as WorkshopsCodeParticipantsNewsroomRouteImport } from "./routes/workshops.$code.participants_.newsroom"
import { Route as WorkshopsCodeParticipantsStageRouteImport } from "./routes/workshops.$code.participants_.stage"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsCodeParticipantsRoute =
  WorkshopsCodeParticipantsRouteImport.update({
    id: "/workshops/$code/participants",
    path: "/workshops/$code/participants",
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkshopsCodeParticipantsTeamIdRoute =
  WorkshopsCodeParticipantsTeamIdRouteImport.update({
    id: "/workshops/$code/participants_/$teamId",
    path: "/workshops/$code/participants/$teamId",
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkshopsCodeParticipantsNewsroomRoute =
  WorkshopsCodeParticipantsNewsroomRouteImport.update({
    id: "/workshops/$code/participants_/newsroom",
    path: "/workshops/$code/participants/newsroom",
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkshopsCodeParticipantsStageRoute =
  WorkshopsCodeParticipantsStageRouteImport.update({
    id: "/workshops/$code/participants_/stage",
    path: "/workshops/$code/participants/stage",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/workshops/$code/participants": typeof WorkshopsCodeParticipantsRoute
  "/workshops/$code/participants/$teamId": typeof WorkshopsCodeParticipantsTeamIdRoute
  "/workshops/$code/participants/newsroom": typeof WorkshopsCodeParticipantsNewsroomRoute
  "/workshops/$code/participants/stage": typeof WorkshopsCodeParticipantsStageRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/workshops/$code/participants": typeof WorkshopsCodeParticipantsRoute
  "/workshops/$code/participants/$teamId": typeof WorkshopsCodeParticipantsTeamIdRoute
  "/workshops/$code/participants/newsroom": typeof WorkshopsCodeParticipantsNewsroomRoute
  "/workshops/$code/participants/stage": typeof WorkshopsCodeParticipantsStageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/workshops/$code/participants": typeof WorkshopsCodeParticipantsRoute
  "/workshops/$code/participants_/$teamId": typeof WorkshopsCodeParticipantsTeamIdRoute
  "/workshops/$code/participants_/newsroom": typeof WorkshopsCodeParticipantsNewsroomRoute
  "/workshops/$code/participants_/stage": typeof WorkshopsCodeParticipantsStageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/workshops/$code/participants"
    | "/workshops/$code/participants/$teamId"
    | "/workshops/$code/participants/newsroom"
    | "/workshops/$code/participants/stage"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/workshops/$code/participants"
    | "/workshops/$code/participants/$teamId"
    | "/workshops/$code/participants/newsroom"
    | "/workshops/$code/participants/stage"
  id:
    | "__root__"
    | "/"
    | "/workshops/$code/participants"
    | "/workshops/$code/participants_/$teamId"
    | "/workshops/$code/participants_/newsroom"
    | "/workshops/$code/participants_/stage"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkshopsCodeParticipantsRoute: typeof WorkshopsCodeParticipantsRoute
  WorkshopsCodeParticipantsTeamIdRoute: typeof WorkshopsCodeParticipantsTeamIdRoute
  WorkshopsCodeParticipantsNewsroomRoute: typeof WorkshopsCodeParticipantsNewsroomRoute
  WorkshopsCodeParticipantsStageRoute: typeof WorkshopsCodeParticipantsStageRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workshops/$code/participants": {
      id: "/workshops/$code/participants"
      path: "/workshops/$code/participants"
      fullPath: "/workshops/$code/participants"
      preLoaderRoute: typeof WorkshopsCodeParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workshops/$code/participants_/$teamId": {
      id: "/workshops/$code/participants_/$teamId"
      path: "/workshops/$code/participants/$teamId"
      fullPath: "/workshops/$code/participants/$teamId"
      preLoaderRoute: typeof WorkshopsCodeParticipantsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workshops/$code/participants_/newsroom": {
      id: "/workshops/$code/participants_/newsroom"
      path: "/workshops/$code/participants/newsroom"
      fullPath: "/workshops/$code/participants/newsroom"
      preLoaderRoute: typeof WorkshopsCodeParticipantsNewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/workshops/$code/participants_/stage": {
      id: "/workshops/$code/participants_/stage"
      path: "/workshops/$code/participants/stage"
      fullPath: "/workshops/$code/participants/stage"
      preLoaderRoute: typeof WorkshopsCodeParticipantsStageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkshopsCodeParticipantsRoute: WorkshopsCodeParticipantsRoute,
  WorkshopsCodeParticipantsTeamIdRoute: WorkshopsCodeParticipantsTeamIdRoute,
  WorkshopsCodeParticipantsNewsroomRoute:
    WorkshopsCodeParticipantsNewsroomRoute,
  WorkshopsCodeParticipantsStageRoute: WorkshopsCodeParticipantsStageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
