/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkshopsCodeParticipantsRouteImport } from './routes/workshops.$code.participants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopsCodeParticipantsRoute =
  WorkshopsCodeParticipantsRouteImport.update({
    id: '/workshops/$code/participants',
    path: '/workshops/$code/participants',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workshops/$code/participants': typeof WorkshopsCodeParticipantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workshops/$code/participants': typeof WorkshopsCodeParticipantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workshops/$code/participants': typeof WorkshopsCodeParticipantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workshops/$code/participants'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workshops/$code/participants'
  id: '__root__' | '/' | '/workshops/$code/participants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkshopsCodeParticipantsRoute: typeof WorkshopsCodeParticipantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshops/$code/participants': {
      id: '/workshops/$code/participants'
      path: '/workshops/$code/participants'
      fullPath: '/workshops/$code/participants'
      preLoaderRoute: typeof WorkshopsCodeParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkshopsCodeParticipantsRoute: WorkshopsCodeParticipantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
